var organs_dict = { # [frame]
	"WILD": [94],
	"Heart": [95],
	"Spleen": [96],
	"Gallbladder": [97],
	"Bowels": [98],
	"Tongue": [99],
	"Lungs": [100],
	"Trachea": [101],
	"Liver": [102],
	"Teeth": [103],
	"Pancreas": [104],
	"Eyes": [105],
	"Appendix": [106],
	"Bladder": [107],
	"Brain": [108],
	"Esophagus": [109],
	"Tonsils": [110],
	"Stomach": [111],
	"Thyroid": [112],
	"Kidneys": [113],
	"Nose": [114],
	"Skin": [115],
	"Bones": [116],
	"Skeletal Muscles": [117]
}
# types: affliction, wild, necrosis, metastasis, resistance, cure, poison, tactical, bureaucracy
var attack_dict = {# [type, is_instant, [afflicts/removes], special_func]
	"Immunity Boost!": ["Resistance", true, [], null], #*
	"Vaccine!": ["Resistance", false, [], null], #*
	"Contagious!": ["Tactical", true, ["All"], null], #*
	"Necrosis!": ["Necrosis", false, ["All"], null], #*
	"Necrosis!F": ["Necrosis", true, ["All"], null], #*
	"Sedate!": ["Tactical", false, [], null], #*
	"Metastasis!": ["Metastasis", true, ["All"], null], #*
	"Cavity!": ["Affliction", false, ["Teeth"], null],
	"Hypochondria!": ["Wild", false, ["All"], null],
	"Ruptured Appendix!": ["Affliction", false, ["AppendixR"], null],
	"Transplant!": ["Tactical", false, [], null], #*
	"Gallstones!": ["Affliction", false, ["Gallbladder"], null],
	"Overactive Bladder!": ["Affliction", false, ["Gallbladder"], null],
	"Lacerated Spleen!": ["Affliction", false, ["Bladder"], null],
	"Hemorrhage!": [],
	"Botched Surgery!": [],
	"Stroke!": [],
	"Research!": [],
	"POISONED!": [],
	"Chronic Strep Throat!": [],
	"Crohn's!": [],
	"Appendicitis!": [],
	"Biliary Dyskinesia!": [],
	"Hepatosplenomegaly": [],
	"Chart Mix-up": [],
	"Glaucoma!": [],
	"Cystic Fibrosis!": [],
	"Medical Miracle!": [],
	"Love!": [],
	"Hyperplenism!": [],
	"Thyroiditis!": [],
	"Tracheal Stenosis!": [],
	"Arrhythmia!": [],
	"Total Colectomy!": [],
	"Infection!": [],
	"Vomit!": [],
	"Calcium Stones!": [],
	"Tonsil Stones!": [],
	"IBS-d!": [],
	"Neglect!": [],
	"Benign Tumor": [],
	"Esophageal Stricture!": [],
	"Heartburn!": [],
	"Hyperthyroidism!": [],
	"Foreign Object in Eye!": [],
	"Kidney Donor!": [],
	"Tonsillitis!": [],
	"Inflamed Taste Bud": [],
	"Scalding Coffee!": [],
	"Diabetes!": [],
	"Fatty Liver!": [],
	"Stomach Ulcer!": [],
	"Asthma!": [],
	"Hypothyroidism!": [],
	"Cirrhosis!": [],
	"Urinary Tract Infection!": [],
	"Mental Illness!": [],
	"Walking Pneumonia!": [],
	"Pancreatitis!": [],
	"Enamel Erosion!": [],
	"Heart Attack!": [],
	"Conjunctivitis!": [],
	"Medicine!": [],
	"Narcolepsy!": [],
	"Congestion!": [],
	"Outbreak!": [],
	"Malpractice!": [],
	"It's Alive!": [],
	"Common Cold!": [],
	"Nosebleed!": [],
	"Acne!": [],
	"Muscle Contusion!": [],
	"Day Old Burrito!": [],
	"Cryopreservation!": [],
	"Fracture!": [],
	"By the Book!": [],
	"Osteoporosis!": [],
	"Clinical Audit!": [],
	"Multiple Sclerosis!": [],
	"Tendonitis!": [],
	"Cancer!": [],
	"Upper Respiratory Infection!": [],
	"Muscular Dystrophy!": [],
	"Situs Inversus!": [],
	"Psoriasis!": []
}
